{% set name = "portpicker" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bd507fd6f96f65ee02781f2e674e9dc6c99bbfa6e3c39992e3916204c9d431fa

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv
  skip: true  # [py<36]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools >=40.9.0
  run:
    - python
    - psutil

# >   'Unable to connect to our own portserver.py: %s' % err)
# E   FileNotFoundError: [Errno 2] No such file or directory
# E   _ ERROR at setup of PickUnusedPortTestWithAPortServer.testPickUnusedCanSuccessfullyUsePortServer...
# macOS-specific path length limitation causing Unix socket creation to fail:
{% set deselect_tests = " --deselect=src/tests/portpicker_test.py::PortpickerCommandLineTests::test_command_line_interface" %}
{% set deselect_tests = deselect_tests + " --deselect=src/tests/portpicker_test.py::PickUnusedPortTestWithAPortServer::testGetPortFromPortServer" %}
{% set deselect_tests = deselect_tests + " --deselect=src/tests/portpicker_test.py::PickUnusedPortTestWithAPortServer::testPickUnusedCanSuccessfullyUsePortServer" %}
test:
  source_files:
    - src
  imports:
    - portpicker
  commands:
    - pip check
    - pytest -v src/tests/portpicker_test.py {{ deselect_tests }}
  requires:
    - pip
    - pytest
    - mock

about:
  home: https://pypi.org/project/portpicker
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A library to choose unique available network ports.
  description: |
    Portpicker provides an API to find and return an available
    network port for an application to bind to. Ideally suited
    for use from unittests or for test harnesses that launch
    local servers.
  dev_url: https://github.com/google/python_portpicker
  doc_url: https://github.com/google/python_portpicker/blob/main/README.md

extra:
  recipe-maintainers:
    - nehaljwani
