{% set name = "portpicker" %}
{% set version = "1.6.0" %}
{% set file_ext = "tar.gz" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ file_ext }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  sha256: bd507fd6f96f65ee02781f2e674e9dc6c99bbfa6e3c39992e3916204c9d431fa

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv
  skip: true  # [py<36]

requirements:
  host:
    - python
    - setuptools >=40.9.0
    - pip
    - wheel
  run:
    - python
    - psutil

test:
  requires:
    - pip
  imports:
    - portpicker
  source_files:
    - src/tests
  commands:
    - python src/tests/portpicker_test.py
    - pip check

about:
  home: https://pypi.org/project/portpicker/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A library to choose unique available network ports.
  description: |
    Portpicker provides an API to find and return an available
    network port for an application to bind to. Ideally suited
    for use from unittests or for test harnesses that launch
    local servers.
  dev_url: https://github.com/google/python_portpicker
  doc_url: https://github.com/google/python_portpicker

extra:
  recipe-maintainers:
    - nehaljwani
